# Generated by Django 4.2.7 on 2024-03-19 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("updated_datetime", models.DateTimeField(auto_now_add=True)),
                ("company_name", models.CharField(max_length=100, unique=True)),
                ("company_url", models.URLField(unique=True)),
                ("company_logo", models.ImageField(upload_to="company_logo/")),
                ("company_email", models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Jobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("updated_datetime", models.DateTimeField(auto_now_add=True)),
                ("job_title", models.CharField(max_length=100, unique=True)),
                ("job_listing_url", models.URLField(unique=True)),
                (
                    "job_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("job_salary", models.IntegerField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jobs.company"
                    ),
                ),
            ],
        ),
    ]
